// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20230926202729_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryName = "informatica",
                            Description = "description",
                            ImageUrl = "localhost",
                            Name = "name",
                            Price = 2000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
